trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self
  fetchDepth: 0

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Oobeya-Sonar'
    scannerMode: 'dotnet'
    projectKey: 'ExpenseTracker'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'

- task: SonarQubeAnalyze@7

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

